# src: ./.github/actions/validate-environment/action.yml
# @(#) : composite GitHub Action to validate runner environment
#
# Copyright (c) 2026- aglabo <https://github.com/aglabo>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "Validate Environment"
description: "Validate GitHub Actions runner environment (Linux AMD64/ARM64, Git, curl)"
author: "aglabo"

branding:
  icon: "check-circle"
  color: "green"

inputs:
  architecture:
    description: "Expected runner architecture: amd64 (x86_64) or arm64 (aarch64). Default: amd64"
    required: false
    default: "amd64"
  fail-fast:
    description: "Fail immediately on first validation error. Set to 'false' to collect all errors before failing. Default: true"
    required: false
    default: "true"
  additional-apps:
    description: "Additional applications to validate (space-separated, format: cmd|app_name|version_extractor|min_version)"
    required: false
    default: ""

outputs:
  status:
    description: "Overall validation status (success or error)"
    value: ${{ steps.summary.outputs.status }}
  message:
    description: "Combined validation result message from all steps"
    value: ${{ steps.summary.outputs.message }}
  validated_apps:
    description: "Comma-separated list of validated application names (from validate-apps step)"
    value: ${{ steps.validate-apps.outputs.validated_apps }}
  validated_count:
    description: "Number of successfully validated applications"
    value: ${{ steps.validate-apps.outputs.validated_count }}
  failed_apps:
    description: "Comma-separated list of failed application names (empty if all passed)"
    value: ${{ steps.validate-apps.outputs.failed_apps }}
  failed_count:
    description: "Number of failed applications (0 if all passed)"
    value: ${{ steps.validate-apps.outputs.failed_count }}

runs:
  using: "composite"
  steps:
    - name: "Validate OS and environment variables"
      id: validate-os
      shell: bash
      env:
        EXPECTED_ARCHITECTURE: ${{ inputs.architecture }}
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/scripts/validate-os.sh"

    - name: "Validate required applications"
      id: validate-apps
      shell: bash
      env:
        FAIL_FAST: ${{ inputs.fail-fast }}
      run: |
        set -euo pipefail
        if [ -n "${{ inputs.additional-apps }}" ]; then
          "${GITHUB_ACTION_PATH}/scripts/validate-apps.sh" ${{ inputs.additional-apps }}
        else
          "${GITHUB_ACTION_PATH}/scripts/validate-apps.sh"
        fi

    - name: "Summary"
      id: summary
      shell: bash
      run: |
        set -euo pipefail

        # Get status and messages from each step
        OS_STATUS="${{ steps.validate-os.outputs.status }}"
        OS_MESSAGE="${{ steps.validate-os.outputs.message }}"
        APPS_STATUS="${{ steps.validate-apps.outputs.status }}"
        APPS_MESSAGE="${{ steps.validate-apps.outputs.message }}"

        # Combine messages
        COMBINED_MESSAGE="${OS_MESSAGE}; ${APPS_MESSAGE}"

        # Overall status is success only if both are success
        if [ "$OS_STATUS" = "success" ] && [ "$APPS_STATUS" = "success" ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "message=${COMBINED_MESSAGE}" >> $GITHUB_OUTPUT
        else
          echo "status=error" >> $GITHUB_OUTPUT
          echo "message=${COMBINED_MESSAGE}" >> $GITHUB_OUTPUT
        fi
