name: Release
description: Plan and track a release across packages (core & aggregators)
title: "[Release] vX.Y.Z: "
labels:
  - release
assignees: []

body:
  - type: markdown
    attributes:
      value: "## Release Basic Info"

  - type: input
    id: version
    attributes:
      label: Version
      description: Semantic version (ex. v1.2.3)
    validations:
      required: true

  - type: dropdown
    id: release_type
    attributes:
      label: Release Type
      options:
        - pre-release
        - stable
    validations:
      required: true

  - type: textarea
    id: release_goal
    attributes:
      label: Release Goal / Scope
      description: |
        Describe the purpose and scope of this release.
        - What is the main goal?
        - What is explicitly out of scope?
    validations:
      required: true

  - type: textarea
    id: included_items
    attributes:
      label: Included Features / Fixes
      description: |
        List features, fixes, or PRs included in this release.
        Use links where possible.

  - type: textarea
    id: excluded_items
    attributes:
      label: Excluded / Deferred Items
      description: |
        Explicitly note items that will NOT be included.

  - type: textarea
    id: release_readiness
    attributes:
      label: Release Readiness Criteria
      description: |
        Conditions that must be satisfied before releasing.
        - Tests and CI are green
        - Required documentation is updated
        - Breaking changes are documented
        - Rollback strategy is defined
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Additional Context"

  - type: textarea
    id: context
    attributes:
      label: Notes / Links
    validations:
      required: false
