name: Task
description: Development, maintenance, or project tasks.
title: "[Task]"
labels: ["task"]

body:
  - type: markdown
    attributes:
      value: |
        **Owner:** (assignee)
        **Reviewer (if needed):**

  - type: dropdown
    id: task_type
    attributes:
      label: Task Type
      description: Select the category that best describes this task.
      options:
        - Development Task
        - Maintenance
        - Documentation
        - Refactoring
        - Security
        - Performance
        - Testing
        - DevOps/CI
    validations:
      required: true

  - type: textarea
    attributes:
      label: Task description
      description: Describe what needs to be done and why.
      placeholder: "Update the build system to support ES2022 target for better performance..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Task Checklist
      description: |
        Concrete steps or checks derived from
        Feature / Release acceptance criteria.
        All checked items are required to consider this task complete.
      placeholder: |
        - [ ] Update TypeScript config to target ES2022
        - [ ] Update build scripts accordingly
        - [ ] Verify all tests pass
        - [ ] Update documentation if needed

  - type: input
    attributes:
      label: Estimated effort
      description: |
        Optional rough estimate.
        This does not represent a commitment.
      placeholder: "2-3 hours / 1 day / 1 week"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: false

  - type: textarea
    attributes:
      label: Dependencies
      description: List any blocking issues, PRs, or prerequisites.
      placeholder: "Depends on #42, requires Node.js 18+ support..."

  - type: textarea
    attributes:
      label: Additional context
      description: Links, references, or other supporting information.
