# src: ./.github/actions/setup-gitleaks/action.yml
# @(#) : composite GitHub Action to setup Gitleaks
#
# Copyright (c) 2026- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "Setup Gitleaks"
description: "Download, verify, and install Gitleaks binary with SHA256 checksum verification (Linux amd64 only)"
author: "aglabo"

branding:
  icon: "download"
  color: "orange"

inputs:
  version:
    description: "Gitleaks version to install"
    required: false
    default: "8.30.0"

runs:
  using: "composite"
  steps:
    - name: "Validate OS compatibility"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/validate-os.sh"

    - name: "Setup installation directories"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/setup-directories.sh"

    - name: "Download Gitleaks binary and checksums"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/download-tool.sh" \
          "gitleaks" \
          "${{ inputs.version }}" \
          "gitleaks" \
          "x64" \
          "${TEMP_DIR}"

    - name: "Verify checksum"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/verify-checksum.sh" \
          "gitleaks" \
          "${{ inputs.version }}" \
          "x64" \
          "${TEMP_DIR}"

    - name: "Extract and install Gitleaks"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/extract-install.sh" \
          "gitleaks" \
          "${TEMP_DIR}" \
          "${BIN_DIR}"

    - name: "Validate installation"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/validate-installation.sh" \
          "gitleaks" \
          "${BIN_DIR}" \
          "gitleaks version"

    - name: "Cleanup temporary files"
      shell: bash
      if: always()
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/cleanup.sh" "${TEMP_DIR:-}"
