# src: ./.github/actions/setup-ghalint/action.yml
# @(#) : composite GitHub Action to setup ghalint
#
# Copyright (c) 2026- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "Setup ghalint"
description: "Download, verify, and install ghalint binary with SHA256 checksum verification (Linux amd64 only)"
author: "aglabo"

branding:
  icon: "download"
  color: "yellow"

inputs:
  version:
    description: "ghalint version to install"
    required: false
    default: "1.5.5"

runs:
  using: "composite"
  steps:
    - name: "Validate OS compatibility"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/validate-os.sh"

    - name: "Setup installation directories"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/setup-directories.sh"

    - name: "Download ghalint binary and checksums"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/download-tool.sh" \
          "ghalint" \
          "${{ inputs.version }}" \
          "suzuki-shunsuke" \
          "amd64" \
          "${TEMP_DIR}"

    - name: "Verify checksum"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/verify-checksum.sh" \
          "ghalint" \
          "${{ inputs.version }}" \
          "amd64" \
          "${TEMP_DIR}"

    - name: "Extract and install ghalint"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/extract-install.sh" \
          "ghalint" \
          "${TEMP_DIR}" \
          "${BIN_DIR}"

    - name: "Validate installation"
      shell: bash
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/validate-installation.sh" \
          "ghalint" \
          "${BIN_DIR}" \
          "ghalint --version"

    - name: "Cleanup temporary files"
      shell: bash
      if: always()
      run: |
        set -euo pipefail
        "${GITHUB_ACTION_PATH}/../scripts/cleanup.sh" "${TEMP_DIR:-}"
